services:
  - type: web
    name: kindly
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.x
    staticPublishPath: .next
    routes:
      - type: rewrite
        source: /_next/*
        destination: /_next/*
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
