services:
  - type: static
    name: kindly
    buildCommand: npm install && npm run build
    publishDirectory: dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
