services:
  - type: web
    name: kindly
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
