services:
  - type: web
    name: kindly
    runtime: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
