services:
  - type: static
    name: kindly
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
