#!/bin/bash

# Change to the kindly directory where our files are located
cd /Users/deandremoore/Desktop/kindly

# Activate virtual environment and run the Python script
source "/Users/deandremoore/Desktop/kindly/venv/bin/activate"
python "/Users/deandremoore/Desktop/kindly/scripts/fetch_cj_data.py"
deactivate
