// Generated by optimize-image-sizes.js
export type ImageSizes = {
  'hero.jpg': 'xl' | 'lg' | 'md' | 'sm';
  'profile': 'lg' | 'md' | 'sm';
  'feature': 'lg' | 'md' | 'sm';
  'logo': 'lg' | 'md' | 'sm';
}

export const imageSizeConfigs = {
  "hero.jpg": {
    "sizes": [
      {
        "width": 1920,
        "suffix": "xl"
      },
      {
        "width": 1280,
        "suffix": "lg"
      },
      {
        "width": 768,
        "suffix": "md"
      },
      {
        "width": 640,
        "suffix": "sm"
      }
    ],
    "quality": 80
  },
  "profile": {
    "sizes": [
      {
        "width": 400,
        "suffix": "lg"
      },
      {
        "width": 300,
        "suffix": "md"
      },
      {
        "width": 200,
        "suffix": "sm"
      }
    ],
    "quality": 85
  },
  "feature": {
    "sizes": [
      {
        "width": 800,
        "suffix": "lg"
      },
      {
        "width": 600,
        "suffix": "md"
      },
      {
        "width": 400,
        "suffix": "sm"
      }
    ],
    "quality": 80
  },
  "logo": {
    "sizes": [
      {
        "width": 200,
        "suffix": "lg"
      },
      {
        "width": 150,
        "suffix": "md"
      },
      {
        "width": 100,
        "suffix": "sm"
      }
    ],
    "quality": 90
  }
} as const;
